Config = {}
Config.Locale = 'es'

Config['Preventions'] = true
Config['DeleteBrokenCars'] = true
Config['AntiACBypass'] = true
Config['AntiBlackweapons'] = true
Config['AntiSuperJump'] = true
Config['AntiTeleport'] = true
Config['AntiCarBlack'] = true
Config['AntiSpectate'] = true
Config['AntiFreeCam'] = true
Config['AntiNoclip'] = true
Config['AntiGodmode'] = true
Config['PlayerProtection'] = true
Config['AntiPedAttack'] = true
Config['AntiWeaponDMGModifier'] = true
Config['AntiPedCrasher'] = true
Config['AntiSpeed'] = true
Config['AntiProjectile'] = true
Config['AntiBlips'] = true
Config['AntiKey'] = true
Config['AntiMenyoo'] = true

Config.WeaponBL = { "WEAPON_RAILGUN", "WEAPON_GARBAGEBAG", "WEAPON_SNSPISTOL_MK2", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_REVOLVER_MK2", "WEAPON_DOUBLEACTION", "WEAPON_SMG_MK2", "WEAPON_MACHINEPISTOL", "WEAPON_MINISMG", "WEAPON_RAYCARBINE", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_HEAVYSHOTGUN", "WEAPON_DBSHOTGUN", "WEAPON_AUTOSHOTGUN", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_COMPACTRIFLE", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_COMBATMG_MK2", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE", "WEAPON_MARKSMANRIFLE_MK2", "WEAPON_RPG", "WEAPON_GRENADELAUNCHER", "WEAPON_GRENADELAUNCHER_SMOKE", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMPACTLAUNCHER", "WEAPON_RAYMINIGUN", "WEAPON_GRENADE", "WEAPON_BZGAS", "WEAPON_MOLOTOV", "WEAPON_STICKYBOMB", "WEAPON_PROXMINE", "WEAPON_SNOWBALL", "WEAPON_PIPEBOMB", "WEAPON_BALL", "WEAPON_SMOKEGRENADE", "WEAPON_ROCKET", "WEAPON_EXPLOSION ", "WEAPON_FLARE", "WEAPON_MUSKET" }